version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Australia/Brisbane
    allow:
      - dependency-type: all
    groups:
      ruby-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Australia/Brisbane
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]
    open-pull-requests-limit: 5
