# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Code
tagline:          'Writings by Toby Smith'
description:      'Thoughts on programming and technology. Made by <a href="mailto:toby@tismith.id.au">Toby Smith</a>.'
url:              http://tismith.id.au

author:
  name:           'Toby Smith'
  email:           toby@tismith.id.au
  twitter:         https://twitter.com/tismith
  linkedin:        http://au.linkedin.com/in/tismith22
  github:          https://github.com/tismith

paginate:         5

github:
  repo:           https://github.com/tismith/tismith.github.io

disqus:
  shortname:      codetismith
