# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Code
tagline:          'Writings by Toby Smith'
description:      'Thoughts on code, covering a variety of interests. Made by <a href="https://twitter.com/tismith" target="_blank">@tismith</a>.'
url:              http://code.tismith.id.au

author:
  name:           'Toby Smith'
  url:            https://twitter.com/tismith

paginate:         5

github:
  repo:           https://github.com/tismith
