# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:categories/:year/:title.html

# Setup
title:            Code
tagline:          'Writings by Toby Smith'
description:      'By <a href="mailto:toby@tismith.id.au">Toby Smith</a>.'
url:              http://tismith.github.io
timezone:         Australia/Brisbane

author:
  name:           'Toby Smith'
  email:          toby@tismith.id.au
  twitter:        https://twitter.com/tismith
  linkedin:       http://au.linkedin.com/in/tismith22
  github:         https://github.com/tismith

paginate:         5

github:
  repo:           https://github.com/tismith/tismith.github.io

disqus:
  shortname:      codetismith

exclude:          [Gemfile, Gemfile.lock, Makefile, README.md]
